2019-06-02 08:48:23,219 : kivy : Factory: 194 symbols loaded
2019-06-02 08:48:23,506 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-06-02 08:48:23,590 : kivy : VideoGstplayer: Using Gstreamer 1.10.4.0
2019-06-02 08:48:23,590 : kivy : Video: Provider: gstplayer
2019-06-02 08:48:23,681 : kivy : Loading MPF-MC controller
2019-06-02 08:48:23,682 : mpfmc : Mission Pinball Framework Media Controller v0.52.2
2019-06-02 08:48:23,683 : mpfmc : Mission Pinball Framework Game Engine v0.52.2
2019-06-02 08:48:23,683 : mpfmc : Machine path: /home/murray/pinball/machines/test
2019-06-02 08:48:23,684 : ConfigProcessor : Cache file not found: /tmp/75a098f7a80ab927cf616400276deb57.mpf_cache
2019-06-02 08:48:23,684 : ConfigProcessor : Loading config from file /usr/local/lib/python3.5/dist-packages/mpfmc/mcconfig.yaml.
2019-06-02 08:48:23,847 : ConfigProcessor : Loading config: /usr/local/lib/python3.5/dist-packages/mpfmc/mcconfig.yaml
2019-06-02 08:48:23,899 : ConfigProcessor : Loading config from file /home/murray/pinball/machines/test/config/config.
2019-06-02 08:48:23,899 : kivy : Error found in file /home/murray/pinball/machines/test/config/config.yaml: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/file_interfaces/yaml_interface.py", line 197, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/commands/mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/core/mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "/usr/local/lib/python3.5/dist-packages/mpfmc/core/mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/usr/local/lib/python3.5/dist-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /home/murray/pinball/machines/test/config/config.yaml: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml
2019-06-02 08:48:23,901 : kivy : Stopping child threads... (0 remaining)
2019-06-02 08:48:23,902 : kivy : All child threads stopped.
